// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StsKlassifikation.DBContext;

namespace StsKlassifikation.Migrations
{
    [DbContext(typeof(ClassificationContext))]
    partial class ClassificationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StsKlassifikation.Model.Facet", b =>
                {
                    b.Property<string>("UUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ansvarlig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrugervendtNoegle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ejer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacetTilhoerer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KlassifikationUUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Livscykluskode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opbygning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ophavsret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanIdentifikator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Publiceret")
                        .HasColumnType("bit");

                    b.Property<string>("RetskildeTekst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplementTekst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UUID");

                    b.HasIndex("KlassifikationUUID");

                    b.ToTable("Facet");
                });

            modelBuilder.Entity("StsKlassifikation.Model.FacetRedaktoer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FacetUUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacetUUID");

                    b.ToTable("FacetRedaktoer");
                });

            modelBuilder.Entity("StsKlassifikation.Model.Klasse", b =>
                {
                    b.Property<string>("UUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Aendringsnotat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ansvarlig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrugervendtNoegle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ejer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacetUUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KlasseTilhoerer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Livscykluskode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Omfang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverordnetKlasse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Retskilde")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soegeord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Tilstand")
                        .HasColumnType("bit");

                    b.Property<string>("Titel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UUID");

                    b.HasIndex("FacetUUID");

                    b.ToTable("Klasse");
                });

            modelBuilder.Entity("StsKlassifikation.Model.KlasseErstatter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KlasseUUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KlasseUUID");

                    b.ToTable("KlasseErstatter");
                });

            modelBuilder.Entity("StsKlassifikation.Model.KlasseLovligeKombinationer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KlasseUUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KlasseUUID");

                    b.ToTable("KlasseLovligeKombination");
                });

            modelBuilder.Entity("StsKlassifikation.Model.KlasseRedaktoer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KlasseUUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KlasseUUID");

                    b.ToTable("KlasseRedaktoer");
                });

            modelBuilder.Entity("StsKlassifikation.Model.KlasseSideordnet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KlasseUUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KlasseUUID");

                    b.ToTable("KlasseSideordnet");
                });

            modelBuilder.Entity("StsKlassifikation.Model.KlasseTilfoejelse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KlasseUUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KlasseUUID");

                    b.ToTable("KlasseTilfoejelse");
                });

            modelBuilder.Entity("StsKlassifikation.Model.Klassifikation", b =>
                {
                    b.Property<string>("UUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ansvarlig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrugervendtNoegle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ejer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Livscykluskode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Publiceret")
                        .HasColumnType("bit");

                    b.Property<bool>("Synkroniser")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UUID");

                    b.ToTable("Klassifikation");
                });

            modelBuilder.Entity("StsKlassifikation.Model.Facet", b =>
                {
                    b.HasOne("StsKlassifikation.Model.Klassifikation", "Klassifikation")
                        .WithMany("Facetter")
                        .HasForeignKey("KlassifikationUUID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StsKlassifikation.Model.FacetRedaktoer", b =>
                {
                    b.HasOne("StsKlassifikation.Model.Facet", "Facet")
                        .WithMany("Redaktoerer")
                        .HasForeignKey("FacetUUID");
                });

            modelBuilder.Entity("StsKlassifikation.Model.Klasse", b =>
                {
                    b.HasOne("StsKlassifikation.Model.Facet", "Facet")
                        .WithMany("Klasser")
                        .HasForeignKey("FacetUUID");
                });

            modelBuilder.Entity("StsKlassifikation.Model.KlasseErstatter", b =>
                {
                    b.HasOne("StsKlassifikation.Model.Klasse", "Klasse")
                        .WithMany("Erstatter")
                        .HasForeignKey("KlasseUUID");
                });

            modelBuilder.Entity("StsKlassifikation.Model.KlasseLovligeKombinationer", b =>
                {
                    b.HasOne("StsKlassifikation.Model.Klasse", "Klasse")
                        .WithMany("LovligeKombinationer")
                        .HasForeignKey("KlasseUUID");
                });

            modelBuilder.Entity("StsKlassifikation.Model.KlasseRedaktoer", b =>
                {
                    b.HasOne("StsKlassifikation.Model.Klasse", "Klasse")
                        .WithMany("Redaktoerer")
                        .HasForeignKey("KlasseUUID");
                });

            modelBuilder.Entity("StsKlassifikation.Model.KlasseSideordnet", b =>
                {
                    b.HasOne("StsKlassifikation.Model.Klasse", "Klasse")
                        .WithMany("Sideordnet")
                        .HasForeignKey("KlasseUUID");
                });

            modelBuilder.Entity("StsKlassifikation.Model.KlasseTilfoejelse", b =>
                {
                    b.HasOne("StsKlassifikation.Model.Klasse", "Klasse")
                        .WithMany("Tilfoejelser")
                        .HasForeignKey("KlasseUUID");
                });
#pragma warning restore 612, 618
        }
    }
}
